export const TECH_NODES = [
  // FRONTEND
  {
    id: 'react',
    name: 'React.js',
    category: 'FRONTEND',
    role: 'Core UI & Component Architecture',
    usedFor: 'Declarative component rendering, state orchestration, and responsive web interface foundation.',
    related: ['react-router', 'redux', 'context-api', 'axios', 'framer-motion', 'r3f', 'express'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'javascript',
    name: 'JavaScript (ES6+)',
    category: 'FRONTEND',
    role: 'Core Language Environment',
    usedFor: 'Asynchronous event driven processing, closures, DOM orchestration, and full-stack logic execution.',
    related: ['react', 'node', 'express'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'vite',
    name: 'Vite',
    category: 'FRONTEND',
    role: 'Build Tool & Dev Server',
    usedFor: 'Lightning fast HMR, optimized ES modules bundling, and production asset minification.',
    related: ['react'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'react-router',
    name: 'React Router DOM',
    category: 'FRONTEND',
    role: 'Client-Side Navigation',
    usedFor: 'Dynamic route matching, protected route guards, lazy loading, and deep linking.',
    related: ['react', 'axios'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'axios',
    name: 'Axios',
    category: 'FRONTEND',
    role: 'HTTP Client & API Layer',
    usedFor: 'REST API requests, JWT bearer auth interceptors, and automated response transformations.',
    related: ['react', 'express', 'jwt'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'redux',
    name: 'Redux Toolkit',
    category: 'FRONTEND',
    role: 'Global State Management',
    usedFor: 'Predictable centralized application state, RTK Query async thunks, and state persistence.',
    related: ['react', 'react-redux', 'axios'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'react-redux',
    name: 'React Redux',
    category: 'FRONTEND',
    role: 'React State Binding',
    usedFor: 'Binding Redux store slices to React component sub-trees with optimized selector hooks.',
    related: ['redux', 'react'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'context-api',
    name: 'Context API',
    category: 'FRONTEND',
    role: 'Lightweight State Provider',
    usedFor: 'Theme tokens, user session state, and lightweight component tree scope sharing.',
    related: ['react'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    category: 'FRONTEND',
    role: 'Utility-First Styling Engine',
    usedFor: 'Custom dark obsidian design system, responsive breakpoints, and glassmorphism styling.',
    related: ['react'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'antd',
    name: 'Ant Design',
    category: 'FRONTEND',
    role: 'Enterprise UI Components',
    usedFor: 'Structured tables, complex forms, enterprise design layout patterns, and data grids.',
    related: ['react'],
    projects: ['all', 'moonchat'],
  },
  {
    id: 'mui',
    name: 'Material UI',
    category: 'FRONTEND',
    role: 'Component System',
    usedFor: 'Accessible UI primitives, modal dialogs, and customizable theme palettes.',
    related: ['react'],
    projects: ['all'],
  },
  {
    id: 'framer-motion',
    name: 'Framer Motion',
    category: 'FRONTEND',
    role: 'Component Animation Engine',
    usedFor: 'Layout animations, staggered list reveals, modal transitions, and spring physics.',
    related: ['react', 'gsap'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'gsap',
    name: 'GSAP & ScrollTrigger',
    category: 'FRONTEND',
    role: 'High Performance Animation',
    usedFor: 'Complex timeline choreography, scroll-driven canvas animations, and SVG morphing.',
    related: ['framer-motion', 'lenis'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'lenis',
    name: 'Lenis',
    category: 'FRONTEND',
    role: 'Smooth Scroll Orchestration',
    usedFor: 'Normalized smooth wheel scrolling and parallax section alignment.',
    related: ['gsap'],
    projects: ['all'],
  },
  {
    id: 'three',
    name: 'Three.js',
    category: 'FRONTEND',
    role: 'Core 3D WebGL Engine',
    usedFor: 'Low level 3D mesh creation, custom shader materials, camera lighting, and scene rendering.',
    related: ['r3f', 'drei'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'r3f',
    name: 'React Three Fiber',
    category: 'FRONTEND',
    role: 'React 3D Scene Container',
    usedFor: 'Declarative Three.js scene graphs, reactive 3D canvas rendering, and frame loop hooks.',
    related: ['three', 'drei', 'react'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'drei',
    name: 'Drei',
    category: 'FRONTEND',
    role: '3D Helper Library',
    usedFor: 'Orbit controls, metallic environment maps, text geometries, and GLTF model loaders.',
    related: ['r3f', 'three'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'react-hook-form',
    name: 'React Hook Form',
    category: 'FRONTEND',
    role: 'Form State Management',
    usedFor: 'Uncontrolled high performance form inputs, error handling, and submit validation.',
    related: ['zod'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'zod',
    name: 'Zod / Yup',
    category: 'FRONTEND',
    role: 'Schema Validation',
    usedFor: 'Type-safe object schema validation for forms, API requests, and environment variables.',
    related: ['react-hook-form', 'joi'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'recharts',
    name: 'Recharts / Chart.js',
    category: 'FRONTEND',
    role: 'Data Visualization',
    usedFor: 'Interactive analytics charts, system health graphs, and spending metrics.',
    related: ['react'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'lucide',
    name: 'Lucide React',
    category: 'FRONTEND',
    role: 'Iconography System',
    usedFor: 'Clean modern vector icons for UI state indication and navigation elements.',
    related: ['react'],
    projects: ['all', 'gochat', 'moonchat'],
  },

  // BACKEND
  {
    id: 'node',
    name: 'Node.js',
    category: 'BACKEND',
    role: 'Server Runtime Environment',
    usedFor: 'Non-blocking I/O event loop server runtime powering APIs, microservices, and queue workers.',
    related: ['express', 'mongodb', 'redis', 'bullmq'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'express',
    name: 'Express.js',
    category: 'BACKEND',
    role: 'Web Application Framework',
    usedFor: 'Routing endpoints, middleware chaining, JSON request parsing, and error handling.',
    related: ['node', 'cors', 'jwt', 'multer', 'socketio'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'cors',
    name: 'cors',
    category: 'BACKEND',
    role: 'Cross-Origin Resource Sharing',
    usedFor: 'Origin domain restrictions, allowed headers, and pre-flight HTTP verification.',
    related: ['express', 'helmet'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'dotenv',
    name: 'dotenv',
    category: 'BACKEND',
    role: 'Environment Config Manager',
    usedFor: 'Securely parsing environment secrets, database URIs, and API credentials.',
    related: ['node'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'helmet',
    name: 'helmet',
    category: 'BACKEND',
    role: 'HTTP Security Headers',
    usedFor: 'Securing Express apps by setting HTTP security headers (XSS, CSP, HSTS).',
    related: ['express', 'rate-limit'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'rate-limit',
    name: 'express-rate-limit',
    category: 'BACKEND',
    role: 'API Rate Limiting Guard',
    usedFor: 'Preventing brute-force attacks and abuse by capping client request frequencies.',
    related: ['express', 'redis'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'joi',
    name: 'Joi',
    category: 'BACKEND',
    role: 'Backend Request Validator',
    usedFor: 'Validating payload bodies, route parameters, and query strings prior to controller logic.',
    related: ['express', 'zod'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'multer',
    name: 'Multer',
    category: 'BACKEND',
    role: 'File Upload Middleware',
    usedFor: 'Handling multipart/form-data upload streams and buffering temporary image/PDF files.',
    related: ['cloudinary', 'express'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary SDK',
    category: 'BACKEND',
    role: 'Cloud Media Storage',
    usedFor: 'Automated image/file compression, CDN hosting, transformation, and asset delivery.',
    related: ['multer'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'nodemailer',
    name: 'Nodemailer',
    category: 'BACKEND',
    role: 'Transactional Email & OTP',
    usedFor: 'Sending email verification tokens, OTP password resets, and automated system alerts.',
    related: ['node'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'bullmq',
    name: 'BullMQ',
    category: 'BACKEND',
    role: 'Background Processing & Queues',
    usedFor: 'Offloading heavy asynchronous AI tasks, email dispatches, and PDF rendering away from main API thread.',
    related: ['redis', 'node'],
    projects: ['all', 'gochat'],
  },

  // DATABASE & CACHING
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'DATABASE & CACHING',
    role: 'NoSQL Document Database',
    usedFor: 'Flexible JSON document storage, aggregation pipelines, and high volume write operations.',
    related: ['mongoose', 'vector-search', 'redis'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'mongoose',
    name: 'Mongoose',
    category: 'DATABASE & CACHING',
    role: 'MongoDB ODM & Modeling',
    usedFor: 'Strict schema definitions, model validation, middleware hooks, and population joins.',
    related: ['mongodb', 'express'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'vector-search',
    name: 'MongoDB Vector Search',
    category: 'DATABASE & CACHING',
    role: 'Vector Indexing & Retrieval',
    usedFor: 'Storing high-dimensional AI vector embeddings and performing ANN similarity searches for RAG.',
    related: ['mongodb', 'rag', 'openai'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'DATABASE & CACHING',
    role: 'In-Memory Cache & Key-Value Store',
    usedFor: 'Sub-millisecond query caching, user session storage, AI response caching, and BullMQ backing.',
    related: ['bullmq', 'mongodb', 'express'],
    projects: ['all', 'gochat'],
  },

  // AI & INTELLIGENCE
  {
    id: 'openai',
    name: 'OpenAI APIs',
    category: 'AI & INTELLIGENCE',
    role: 'LLM & Embedding Models',
    usedFor: 'GPT-4o text generation, structured JSON mode output, and text-embedding-3 vectors.',
    related: ['rag', 'vector-search', 'gemini'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'gemini',
    name: 'Google Gemini APIs',
    category: 'AI & INTELLIGENCE',
    role: 'Multimodal Generative AI',
    usedFor: 'High-speed context processing, document analysis, and fallback LLM routing.',
    related: ['openai', 'rag'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'prompt-eng',
    name: 'Prompt Engineering',
    category: 'AI & INTELLIGENCE',
    role: 'Context & Persona Design',
    usedFor: 'Designing system prompts, zero/few-shot chains, output schema constraints, and anti-hallucination rules.',
    related: ['openai', 'gemini', 'rag'],
    projects: ['all', 'gochat'],
  },
  {
    id: 'rag',
    name: 'Retrieval-Augmented Gen (RAG)',
    category: 'AI & INTELLIGENCE',
    role: 'Knowledge Grounding Engine',
    usedFor: 'Chunking raw files, generating embeddings, injecting relevant context into LLM prompts.',
    related: ['vector-search', 'openai', 'mongodb'],
    projects: ['all', 'gochat'],
  },

  // REAL-TIME
  {
    id: 'socketio',
    name: 'Socket.IO',
    category: 'REAL-TIME',
    role: 'WebSockets & Live Events',
    usedFor: 'Bi-directional real-time chat rooms, live typing indicators, online status, and instant updates.',
    related: ['express', 'node', 'webrtc'],
    projects: ['all', 'moonchat'],
  },
  {
    id: 'webrtc',
    name: 'WebRTC',
    category: 'REAL-TIME',
    role: 'Peer-to-Peer Media Streams',
    usedFor: 'Ultra low-latency audio/video streaming directly between client peers via STUN/TURN signaling.',
    related: ['socketio'],
    projects: ['all', 'moonchat'],
  },

  // AUTHENTICATION & SECURITY
  {
    id: 'jwt',
    name: 'JSON Web Token (JWT)',
    category: 'AUTHENTICATION & SECURITY',
    role: 'Stateless Authorization',
    usedFor: 'Signing access tokens & refresh tokens, authorizing REST endpoints and WebSocket handshakes.',
    related: ['express', 'bcrypt', 'passport'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'bcrypt',
    name: 'bcryptjs',
    category: 'AUTHENTICATION & SECURITY',
    role: 'Password Hashing Engine',
    usedFor: 'Salted multi-round password hashing to prevent rainbow table attacks.',
    related: ['jwt', 'mongodb'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'passport',
    name: 'Passport.js & OAuth',
    category: 'AUTHENTICATION & SECURITY',
    role: 'Authentication Middleware',
    usedFor: 'Google & GitHub OAuth 2.0 single-sign-on integration strategies.',
    related: ['express', 'jwt'],
    projects: ['all', 'gochat', 'moonchat'],
  },

  // TOOLS & DEPLOYMENT
  {
    id: 'git',
    name: 'Git & GitHub',
    category: 'DEVELOPER TOOLS & DEPLOYMENT',
    role: 'Version Control & CI/CD',
    usedFor: 'Source code management, branch workflows, pull requests, and automated deployment triggers.',
    related: ['vercel', 'render'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'postman',
    name: 'Postman',
    category: 'DEVELOPER TOOLS & DEPLOYMENT',
    role: 'API Testing & Collection',
    usedFor: 'Endpoint testing, environment variable mock suites, and REST documentation.',
    related: ['express'],
    projects: ['all', 'gochat', 'moonchat'],
  },
  {
    id: 'render',
    name: 'Render / Netlify / Vercel',
    category: 'DEVELOPER TOOLS & DEPLOYMENT',
    role: 'Cloud Deployment Platform',
    usedFor: 'Zero downtime Node.js API hosting, static frontend CDN distribution, and SSL automation.',
    related: ['git'],
    projects: ['all', 'gochat', 'moonchat'],
  },
];
